/**
 * Industry Template Catalog
 * Each template defines CSS variables + layout + enabled components
 * Templates are snapshots — editing master does NOT break existing cards
 */

export interface IndustryTemplate {
  id: string;
  name: string;
  industry: string;
  industryGroup: string;
  description: string;
  font: string;
  headingFont: string;
  // CSS variables
  background: string;       // --theme-background
  surface: string;          // --theme-surface
  primary: string;          // --theme-primary
  secondary: string;        // --theme-secondary
  accent: string;           // --theme-accent
  text: string;             // --theme-text
  muted: string;            // --theme-muted
  border: string;           // --theme-border
  // Style tokens
  buttonStyle: 'filled' | 'outlined' | 'soft' | 'pill' | 'glass';
  cardStyle: 'flat' | 'soft' | 'glass' | 'bordered';
  borderRadius: string;
  headerStyle: 'centered' | 'left' | 'hero' | 'cover' | 'minimal' | 'split';
  avatarShape: 'circle' | 'rounded' | 'square';
  animation: 'none' | 'subtle' | 'smooth';
  // Enabled components (ordered)
  enabledComponents: string[];
  // Locks
  allowColorCustomization: boolean;
  allowFontCustomization: boolean;
  isPublished: boolean;
  isRecommended: boolean;
  tags: string[];
}

// ─── INDUSTRY GROUPS ────────────────────────────────────────
export const INDUSTRY_GROUPS = [
  { id: 'health',     label: 'Health & Medical',  icon: '🏥' },
  { id: 'food',       label: 'Food & Hospitality', icon: '🍽️' },
  { id: 'beauty',     label: 'Beauty & Wellness',  icon: '💆' },
  { id: 'fitness',    label: 'Fitness & Sports',   icon: '💪' },
  { id: 'legal',      label: 'Legal & Finance',    icon: '⚖️' },
  { id: 'realestate', label: 'Real Estate',        icon: '🏠' },
  { id: 'tech',       label: 'Technology',         icon: '💻' },
  { id: 'creative',   label: 'Creative & Design',  icon: '🎨' },
  { id: 'education',  label: 'Education',          icon: '🎓' },
  { id: 'travel',     label: 'Travel & Tourism',   icon: '✈️' },
  { id: 'auto',       label: 'Automotive',         icon: '🚗' },
  { id: 'retail',     label: 'Retail & Commerce',  icon: '🛍️' },
  { id: 'events',     label: 'Events',             icon: '🎉' },
  { id: 'corporate',  label: 'Corporate & Business', icon: '🏢' },
  { id: 'other',      label: 'Other',              icon: '📋' },
];

// ─── INDUSTRY TEMPLATE CATALOG ──────────────────────────────
export const INDUSTRY_TEMPLATES: IndustryTemplate[] = [

  // ════════ FREELANCER / PORTFOLIO ════════
  {
    id: 'freelancer-minimal',
    name: 'Freelancer Minimal',
    industry: 'Freelancer',
    industryGroup: 'corporate',
    description: 'Clean, neutral minimal card for independent professionals',
    font: 'Inter',
    headingFont: 'Inter',
    background: '#FAFAFA',
    surface: '#FFFFFF',
    primary: '#1A1A1A',
    secondary: '#6B7280',
    accent: '#3B82F6',
    text: '#111827',
    muted: '#9CA3AF',
    border: '#E5E7EB',
    buttonStyle: 'pill',
    cardStyle: 'flat',
    borderRadius: '12px',
    headerStyle: 'centered',
    avatarShape: 'circle',
    animation: 'subtle',
    enabledComponents: ['phone', 'email', 'website', 'linkedin', 'github', 'portfolio', 'services', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: true,
    isPublished: true,
    isRecommended: true,
    tags: ['minimal', 'clean', 'freelancer', 'portfolio'],
  },
  {
    id: 'creative-portfolio',
    name: 'Creative Portfolio',
    industry: 'Freelancer',
    industryGroup: 'creative',
    description: 'Bold creative showcase for designers and artists',
    font: 'Poppins',
    headingFont: 'Raleway',
    background: '#0F0F0F',
    surface: '#1A1A1A',
    primary: '#F5F5F5',
    secondary: '#A3A3A3',
    accent: '#F59E0B',
    text: '#F9FAFB',
    muted: '#6B7280',
    border: '#2A2A2A',
    buttonStyle: 'outlined',
    cardStyle: 'bordered',
    borderRadius: '4px',
    headerStyle: 'hero',
    avatarShape: 'square',
    animation: 'smooth',
    enabledComponents: ['phone', 'email', 'instagram', 'behance', 'portfolio', 'gallery', 'services', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: true,
    isPublished: true,
    isRecommended: true,
    tags: ['dark', 'creative', 'designer', 'portfolio', 'bold'],
  },

  // ════════ HEALTH & MEDICAL ════════
  {
    id: 'doctor-clean',
    name: 'Doctor Clean',
    industry: 'Doctor',
    industryGroup: 'health',
    description: 'Trustworthy clean white design for physicians',
    font: 'Inter',
    headingFont: 'Inter',
    background: '#F8FFFE',
    surface: '#FFFFFF',
    primary: '#0D9488',
    secondary: '#134E4A',
    accent: '#99F6E4',
    text: '#0F172A',
    muted: '#64748B',
    border: '#CCFBF1',
    buttonStyle: 'filled',
    cardStyle: 'soft',
    borderRadius: '16px',
    headerStyle: 'centered',
    avatarShape: 'circle',
    animation: 'subtle',
    enabledComponents: ['phone', 'whatsapp', 'email', 'location', 'businessHours', 'services', 'appointment', 'googlereviews', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: true,
    tags: ['medical', 'clean', 'teal', 'doctor', 'health'],
  },
  {
    id: 'doctor-elegant',
    name: 'Doctor Elegant',
    industry: 'Doctor',
    industryGroup: 'health',
    description: 'Sophisticated deep emerald design for specialists',
    font: 'Merriweather',
    headingFont: 'Playfair Display',
    background: '#F0FDF4',
    surface: '#FFFFFF',
    primary: '#166534',
    secondary: '#14532D',
    accent: '#86EFAC',
    text: '#052e16',
    muted: '#6B7280',
    border: '#BBF7D0',
    buttonStyle: 'filled',
    cardStyle: 'soft',
    borderRadius: '12px',
    headerStyle: 'cover',
    avatarShape: 'circle',
    animation: 'subtle',
    enabledComponents: ['phone', 'whatsapp', 'email', 'location', 'services', 'appointment', 'googlereviews'],
    allowColorCustomization: false,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: false,
    tags: ['medical', 'elegant', 'emerald', 'specialist', 'serif'],
  },
  {
    id: 'dentist-bright',
    name: 'Dentist Bright',
    industry: 'Dentist',
    industryGroup: 'health',
    description: 'Bright and welcoming for dental practices',
    font: 'Nunito',
    headingFont: 'Nunito',
    background: '#F0F9FF',
    surface: '#FFFFFF',
    primary: '#0284C7',
    secondary: '#0369A1',
    accent: '#7DD3FC',
    text: '#0C4A6E',
    muted: '#64748B',
    border: '#BAE6FD',
    buttonStyle: 'pill',
    cardStyle: 'soft',
    borderRadius: '20px',
    headerStyle: 'centered',
    avatarShape: 'circle',
    animation: 'subtle',
    enabledComponents: ['phone', 'whatsapp', 'email', 'location', 'businessHours', 'services', 'appointment', 'googlereviews'],
    allowColorCustomization: true,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: true,
    tags: ['dental', 'bright', 'blue', 'friendly', 'health'],
  },
  {
    id: 'clinic-professional',
    name: 'Medical Clinic',
    industry: 'Medical Clinic',
    industryGroup: 'health',
    description: 'Professional clinical design with a modern touch',
    font: 'Inter',
    headingFont: 'Inter',
    background: '#FFFFFF',
    surface: '#F8FAFC',
    primary: '#1E40AF',
    secondary: '#1E3A8A',
    accent: '#DBEAFE',
    text: '#111827',
    muted: '#6B7280',
    border: '#E0E7FF',
    buttonStyle: 'filled',
    cardStyle: 'bordered',
    borderRadius: '8px',
    headerStyle: 'left',
    avatarShape: 'rounded',
    animation: 'none',
    enabledComponents: ['phone', 'email', 'whatsapp', 'location', 'businessHours', 'services', 'team', 'googlereviews', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: true,
    isPublished: true,
    isRecommended: false,
    tags: ['clinic', 'professional', 'corporate', 'health'],
  },
  {
    id: 'pharmacy-clean',
    name: 'Pharmacy',
    industry: 'Pharmacy',
    industryGroup: 'health',
    description: 'Clean and trustworthy for pharmacies',
    font: 'Inter',
    headingFont: 'Inter',
    background: '#F0FDF4',
    surface: '#FFFFFF',
    primary: '#16A34A',
    secondary: '#15803D',
    accent: '#BBF7D0',
    text: '#14532D',
    muted: '#6B7280',
    border: '#D1FAE5',
    buttonStyle: 'filled',
    cardStyle: 'soft',
    borderRadius: '12px',
    headerStyle: 'centered',
    avatarShape: 'rounded',
    animation: 'subtle',
    enabledComponents: ['phone', 'whatsapp', 'location', 'businessHours', 'googlemap', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: false,
    tags: ['pharmacy', 'green', 'health', 'clean'],
  },

  // ════════ LEGAL & FINANCE ════════
  {
    id: 'lawyer-prestige',
    name: 'Lawyer Prestige',
    industry: 'Lawyer',
    industryGroup: 'legal',
    description: 'Authoritative navy and gold for legal professionals',
    font: 'Inter',
    headingFont: 'Playfair Display',
    background: '#FAFAF9',
    surface: '#FFFFFF',
    primary: '#1E3A5F',
    secondary: '#152A47',
    accent: '#B8960C',
    text: '#1A1A2E',
    muted: '#6B7280',
    border: '#E7E5E4',
    buttonStyle: 'filled',
    cardStyle: 'flat',
    borderRadius: '6px',
    headerStyle: 'left',
    avatarShape: 'square',
    animation: 'none',
    enabledComponents: ['phone', 'email', 'whatsapp', 'website', 'location', 'services', 'contact'],
    allowColorCustomization: false,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: true,
    tags: ['legal', 'navy', 'gold', 'authoritative', 'lawyer', 'serif'],
  },
  {
    id: 'law-firm',
    name: 'Law Firm',
    industry: 'Law Firm',
    industryGroup: 'legal',
    description: 'Corporate law firm profile with a prestige feel',
    font: 'Inter',
    headingFont: 'Cormorant Garamond',
    background: '#1A1A1A',
    surface: '#242424',
    primary: '#F5F5F0',
    secondary: '#D4AF37',
    accent: '#D4AF37',
    text: '#F5F5F0',
    muted: '#9CA3AF',
    border: '#333333',
    buttonStyle: 'outlined',
    cardStyle: 'bordered',
    borderRadius: '4px',
    headerStyle: 'cover',
    avatarShape: 'square',
    animation: 'subtle',
    enabledComponents: ['phone', 'email', 'website', 'location', 'services', 'team', 'contact'],
    allowColorCustomization: false,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: false,
    tags: ['legal', 'dark', 'gold', 'prestige', 'corporate', 'serif'],
  },

  // ════════ FOOD & HOSPITALITY ════════
  {
    id: 'restaurant-warm',
    name: 'Restaurant Warm',
    industry: 'Restaurant',
    industryGroup: 'food',
    description: 'Warm terracotta and cream for restaurants',
    font: 'Lato',
    headingFont: 'Playfair Display',
    background: '#FEF9F0',
    surface: '#FFFFFF',
    primary: '#C2410C',
    secondary: '#9A3412',
    accent: '#FED7AA',
    text: '#1C1917',
    muted: '#78716C',
    border: '#FDBA74',
    buttonStyle: 'pill',
    cardStyle: 'soft',
    borderRadius: '16px',
    headerStyle: 'hero',
    avatarShape: 'rounded',
    animation: 'smooth',
    enabledComponents: ['phone', 'whatsapp', 'location', 'businessHours', 'menu', 'gallery', 'instagram', 'tripadvisor', 'googlereviews', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: true,
    tags: ['restaurant', 'warm', 'terracotta', 'food', 'serif'],
  },
  {
    id: 'restaurant-modern',
    name: 'Restaurant Modern',
    industry: 'Restaurant',
    industryGroup: 'food',
    description: 'Sleek dark restaurant card with bold typography',
    font: 'Poppins',
    headingFont: 'Bebas Neue',
    background: '#111111',
    surface: '#1C1C1C',
    primary: '#F5F5F5',
    secondary: '#E5E5E5',
    accent: '#EF4444',
    text: '#F9FAFB',
    muted: '#6B7280',
    border: '#2A2A2A',
    buttonStyle: 'outlined',
    cardStyle: 'glass',
    borderRadius: '8px',
    headerStyle: 'cover',
    avatarShape: 'rounded',
    animation: 'smooth',
    enabledComponents: ['phone', 'whatsapp', 'location', 'businessHours', 'menu', 'gallery', 'instagram', 'tripadvisor', 'booking'],
    allowColorCustomization: true,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: false,
    tags: ['restaurant', 'dark', 'modern', 'bold', 'food'],
  },
  {
    id: 'cafe-cozy',
    name: 'Cafe Cozy',
    industry: 'Cafe',
    industryGroup: 'food',
    description: 'Warm coffee-toned design for cafes and coffee shops',
    font: 'Nunito',
    headingFont: 'Merriweather',
    background: '#FDF6EE',
    surface: '#FFFFFF',
    primary: '#78350F',
    secondary: '#92400E',
    accent: '#FDE68A',
    text: '#1C1917',
    muted: '#92400E',
    border: '#FEF3C7',
    buttonStyle: 'soft',
    cardStyle: 'soft',
    borderRadius: '20px',
    headerStyle: 'centered',
    avatarShape: 'rounded',
    animation: 'subtle',
    enabledComponents: ['phone', 'whatsapp', 'location', 'businessHours', 'menu', 'gallery', 'instagram', 'googlereviews'],
    allowColorCustomization: true,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: true,
    tags: ['cafe', 'cozy', 'brown', 'warm', 'coffee'],
  },
  {
    id: 'hotel-luxury',
    name: 'Hotel Luxury',
    industry: 'Hotel',
    industryGroup: 'travel',
    description: 'Sophisticated champagne and charcoal for hotels',
    font: 'Inter',
    headingFont: 'Cormorant Garamond',
    background: '#FAFAF8',
    surface: '#FFFFFF',
    primary: '#1C1917',
    secondary: '#292524',
    accent: '#D4AF37',
    text: '#1C1917',
    muted: '#78716C',
    border: '#E7E5E4',
    buttonStyle: 'outlined',
    cardStyle: 'flat',
    borderRadius: '4px',
    headerStyle: 'hero',
    avatarShape: 'square',
    animation: 'smooth',
    enabledComponents: ['phone', 'email', 'website', 'whatsapp', 'location', 'gallery', 'booking', 'tripadvisor', 'googlereviews', 'contact'],
    allowColorCustomization: false,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: true,
    tags: ['hotel', 'luxury', 'gold', 'elegant', 'hospitality', 'serif'],
  },

  // ════════ BEAUTY & WELLNESS ════════
  {
    id: 'beauty-salon-rose',
    name: 'Beauty Salon Rose',
    industry: 'Beauty Salon',
    industryGroup: 'beauty',
    description: 'Soft rose and champagne for beauty salons',
    font: 'Nunito',
    headingFont: 'Cormorant Garamond',
    background: '#FFF5F7',
    surface: '#FFFFFF',
    primary: '#BE185D',
    secondary: '#9D174D',
    accent: '#FBCFE8',
    text: '#1F2937',
    muted: '#9CA3AF',
    border: '#FCE7F3',
    buttonStyle: 'pill',
    cardStyle: 'soft',
    borderRadius: '24px',
    headerStyle: 'centered',
    avatarShape: 'circle',
    animation: 'smooth',
    enabledComponents: ['phone', 'whatsapp', 'instagram', 'location', 'businessHours', 'services', 'priceList', 'gallery', 'booking', 'googlereviews'],
    allowColorCustomization: true,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: true,
    tags: ['beauty', 'rose', 'pink', 'salon', 'feminine', 'elegant'],
  },
  {
    id: 'hair-salon-luxury',
    name: 'Hair Salon Luxury',
    industry: 'Hair Salon',
    industryGroup: 'beauty',
    description: 'Black and gold luxury design for high-end salons',
    font: 'Poppins',
    headingFont: 'Playfair Display',
    background: '#0A0A0A',
    surface: '#111111',
    primary: '#F5F5F5',
    secondary: '#D4AF37',
    accent: '#D4AF37',
    text: '#F5F5F5',
    muted: '#6B7280',
    border: '#222222',
    buttonStyle: 'outlined',
    cardStyle: 'glass',
    borderRadius: '8px',
    headerStyle: 'hero',
    avatarShape: 'circle',
    animation: 'smooth',
    enabledComponents: ['phone', 'whatsapp', 'instagram', 'location', 'businessHours', 'services', 'priceList', 'gallery', 'booking'],
    allowColorCustomization: false,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: true,
    tags: ['hair', 'luxury', 'dark', 'gold', 'salon', 'premium'],
  },
  {
    id: 'barbershop-bold',
    name: 'Barbershop Bold',
    industry: 'Barbershop',
    industryGroup: 'beauty',
    description: 'Bold masculine design with vintage barbershop feel',
    font: 'Oswald',
    headingFont: 'Bebas Neue',
    background: '#1A1A1A',
    surface: '#242424',
    primary: '#F5F5F5',
    secondary: '#E5E5E5',
    accent: '#DC2626',
    text: '#F9FAFB',
    muted: '#6B7280',
    border: '#333333',
    buttonStyle: 'filled',
    cardStyle: 'flat',
    borderRadius: '4px',
    headerStyle: 'cover',
    avatarShape: 'square',
    animation: 'subtle',
    enabledComponents: ['phone', 'whatsapp', 'instagram', 'location', 'businessHours', 'services', 'priceList', 'gallery', 'booking'],
    allowColorCustomization: true,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: true,
    tags: ['barbershop', 'dark', 'red', 'bold', 'masculine', 'vintage'],
  },
  {
    id: 'makeup-artist',
    name: 'Makeup Artist',
    industry: 'Makeup Artist',
    industryGroup: 'beauty',
    description: 'Glamorous champagne and nude palette',
    font: 'Raleway',
    headingFont: 'Cormorant Garamond',
    background: '#FEF9F0',
    surface: '#FFFFFF',
    primary: '#92400E',
    secondary: '#78350F',
    accent: '#FDE68A',
    text: '#1C1917',
    muted: '#78716C',
    border: '#FEF3C7',
    buttonStyle: 'soft',
    cardStyle: 'soft',
    borderRadius: '16px',
    headerStyle: 'hero',
    avatarShape: 'circle',
    animation: 'smooth',
    enabledComponents: ['phone', 'whatsapp', 'instagram', 'tiktok', 'gallery', 'services', 'priceList', 'booking'],
    allowColorCustomization: true,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: false,
    tags: ['makeup', 'champagne', 'glamour', 'artist', 'beauty'],
  },
  {
    id: 'spa-serenity',
    name: 'Spa Serenity',
    industry: 'Spa',
    industryGroup: 'beauty',
    description: 'Calm sage and stone palette for spas',
    font: 'Lato',
    headingFont: 'Cormorant Garamond',
    background: '#F5F5F0',
    surface: '#FFFFFF',
    primary: '#4B5563',
    secondary: '#374151',
    accent: '#6EE7B7',
    text: '#1F2937',
    muted: '#9CA3AF',
    border: '#E5E7EB',
    buttonStyle: 'soft',
    cardStyle: 'soft',
    borderRadius: '16px',
    headerStyle: 'centered',
    avatarShape: 'circle',
    animation: 'smooth',
    enabledComponents: ['phone', 'whatsapp', 'location', 'businessHours', 'services', 'priceList', 'gallery', 'booking'],
    allowColorCustomization: true,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: false,
    tags: ['spa', 'sage', 'calm', 'wellness', 'serene'],
  },

  // ════════ FITNESS ════════
  {
    id: 'fitness-gym',
    name: 'Fitness & Gym',
    industry: 'Fitness / Gym',
    industryGroup: 'fitness',
    description: 'High-energy black and lime for gyms',
    font: 'Oswald',
    headingFont: 'Bebas Neue',
    background: '#0A0A0A',
    surface: '#111111',
    primary: '#A3E635',
    secondary: '#65A30D',
    accent: '#A3E635',
    text: '#F5F5F5',
    muted: '#6B7280',
    border: '#1C1C1C',
    buttonStyle: 'filled',
    cardStyle: 'flat',
    borderRadius: '4px',
    headerStyle: 'hero',
    avatarShape: 'square',
    animation: 'smooth',
    enabledComponents: ['phone', 'whatsapp', 'instagram', 'location', 'businessHours', 'services', 'priceList', 'gallery', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: true,
    tags: ['fitness', 'gym', 'dark', 'lime', 'energy', 'bold'],
  },
  {
    id: 'personal-trainer',
    name: 'Personal Trainer',
    industry: 'Personal Trainer',
    industryGroup: 'fitness',
    description: 'Dynamic orange and charcoal for trainers',
    font: 'Poppins',
    headingFont: 'Oswald',
    background: '#FAFAFA',
    surface: '#FFFFFF',
    primary: '#EA580C',
    secondary: '#C2410C',
    accent: '#FED7AA',
    text: '#111827',
    muted: '#6B7280',
    border: '#FED7AA',
    buttonStyle: 'pill',
    cardStyle: 'soft',
    borderRadius: '16px',
    headerStyle: 'hero',
    avatarShape: 'circle',
    animation: 'smooth',
    enabledComponents: ['phone', 'whatsapp', 'instagram', 'youtube', 'services', 'priceList', 'booking', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: true,
    tags: ['trainer', 'orange', 'dynamic', 'fitness', 'sport'],
  },

  // ════════ REAL ESTATE ════════
  {
    id: 'real-estate-charcoal',
    name: 'Real Estate Charcoal',
    industry: 'Real Estate',
    industryGroup: 'realestate',
    description: 'Sophisticated charcoal, sand and bronze',
    font: 'Inter',
    headingFont: 'Raleway',
    background: '#FAFAFA',
    surface: '#FFFFFF',
    primary: '#292524',
    secondary: '#1C1917',
    accent: '#B45309',
    text: '#111827',
    muted: '#6B7280',
    border: '#E7E5E4',
    buttonStyle: 'filled',
    cardStyle: 'flat',
    borderRadius: '8px',
    headerStyle: 'left',
    avatarShape: 'rounded',
    animation: 'subtle',
    enabledComponents: ['phone', 'whatsapp', 'email', 'website', 'instagram', 'googlemap', 'portfolio', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: true,
    isPublished: true,
    isRecommended: true,
    tags: ['real-estate', 'charcoal', 'bronze', 'sophisticated', 'property'],
  },

  // ════════ TECHNOLOGY ════════
  {
    id: 'tech-startup',
    name: 'Tech Startup',
    industry: 'Startup',
    industryGroup: 'tech',
    description: 'Indigo and electric white for tech startups',
    font: 'Inter',
    headingFont: 'Inter',
    background: '#0F0F1A',
    surface: '#151525',
    primary: '#818CF8',
    secondary: '#6366F1',
    accent: '#A5B4FC',
    text: '#F9FAFB',
    muted: '#94A3B8',
    border: '#1E1E35',
    buttonStyle: 'filled',
    cardStyle: 'glass',
    borderRadius: '12px',
    headerStyle: 'centered',
    avatarShape: 'rounded',
    animation: 'smooth',
    enabledComponents: ['phone', 'email', 'linkedin', 'github', 'website', 'portfolio', 'services', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: true,
    isPublished: true,
    isRecommended: true,
    tags: ['tech', 'dark', 'indigo', 'startup', 'developer', 'modern'],
  },
  {
    id: 'software-engineer',
    name: 'Software Engineer',
    industry: 'Software / IT',
    industryGroup: 'tech',
    description: 'Clean dark developer card',
    font: 'JetBrains Mono',
    headingFont: 'Inter',
    background: '#0D1117',
    surface: '#161B22',
    primary: '#58A6FF',
    secondary: '#1F6FEB',
    accent: '#3FB950',
    text: '#E6EDF3',
    muted: '#8B949E',
    border: '#30363D',
    buttonStyle: 'outlined',
    cardStyle: 'bordered',
    borderRadius: '6px',
    headerStyle: 'left',
    avatarShape: 'rounded',
    animation: 'none',
    enabledComponents: ['email', 'github', 'linkedin', 'website', 'portfolio', 'services', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: true,
    isPublished: true,
    isRecommended: true,
    tags: ['developer', 'github', 'dark', 'code', 'engineer'],
  },

  // ════════ CREATIVE ════════
  {
    id: 'photographer',
    name: 'Photographer',
    industry: 'Photographer',
    industryGroup: 'creative',
    description: 'Minimal dark showcase for photographers',
    font: 'Raleway',
    headingFont: 'Raleway',
    background: '#111111',
    surface: '#1A1A1A',
    primary: '#FAFAFA',
    secondary: '#E5E5E5',
    accent: '#FAFAFA',
    text: '#F9FAFB',
    muted: '#9CA3AF',
    border: '#2A2A2A',
    buttonStyle: 'outlined',
    cardStyle: 'flat',
    borderRadius: '0px',
    headerStyle: 'hero',
    avatarShape: 'circle',
    animation: 'smooth',
    enabledComponents: ['phone', 'email', 'instagram', 'website', 'gallery', 'services', 'priceList', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: true,
    isPublished: true,
    isRecommended: true,
    tags: ['photographer', 'dark', 'minimal', 'gallery', 'creative'],
  },
  {
    id: 'designer-purple',
    name: 'Designer Creative',
    industry: 'Designer',
    industryGroup: 'creative',
    description: 'Purple and cream for graphic designers',
    font: 'Poppins',
    headingFont: 'Raleway',
    background: '#F5F3FF',
    surface: '#FFFFFF',
    primary: '#7C3AED',
    secondary: '#6D28D9',
    accent: '#DDD6FE',
    text: '#1F1235',
    muted: '#7C6FA0',
    border: '#EDE9FE',
    buttonStyle: 'pill',
    cardStyle: 'soft',
    borderRadius: '20px',
    headerStyle: 'centered',
    avatarShape: 'circle',
    animation: 'smooth',
    enabledComponents: ['phone', 'email', 'behance', 'instagram', 'linkedin', 'portfolio', 'services', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: true,
    isPublished: true,
    isRecommended: true,
    tags: ['designer', 'purple', 'creative', 'violet', 'portfolio'],
  },
  {
    id: 'marketing-agency',
    name: 'Marketing Agency',
    industry: 'Marketing Agency',
    industryGroup: 'creative',
    description: 'Energetic orange and dark for agencies',
    font: 'Poppins',
    headingFont: 'Poppins',
    background: '#111827',
    surface: '#1F2937',
    primary: '#F97316',
    secondary: '#EA580C',
    accent: '#FED7AA',
    text: '#F9FAFB',
    muted: '#9CA3AF',
    border: '#374151',
    buttonStyle: 'filled',
    cardStyle: 'glass',
    borderRadius: '12px',
    headerStyle: 'hero',
    avatarShape: 'rounded',
    animation: 'smooth',
    enabledComponents: ['phone', 'email', 'linkedin', 'instagram', 'website', 'services', 'portfolio', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: true,
    isPublished: true,
    isRecommended: false,
    tags: ['agency', 'marketing', 'orange', 'dark', 'bold'],
  },

  // ════════ EDUCATION ════════
  {
    id: 'teacher-clean',
    name: 'Teacher / Coach',
    industry: 'Education',
    industryGroup: 'education',
    description: 'Warm and approachable for educators',
    font: 'Nunito',
    headingFont: 'Nunito',
    background: '#FEFCE8',
    surface: '#FFFFFF',
    primary: '#854D0E',
    secondary: '#713F12',
    accent: '#FDE68A',
    text: '#1C1917',
    muted: '#78716C',
    border: '#FEF3C7',
    buttonStyle: 'soft',
    cardStyle: 'soft',
    borderRadius: '20px',
    headerStyle: 'centered',
    avatarShape: 'circle',
    animation: 'subtle',
    enabledComponents: ['phone', 'email', 'whatsapp', 'website', 'location', 'services', 'booking', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: false,
    tags: ['teacher', 'education', 'warm', 'yellow', 'coach'],
  },

  // ════════ CORPORATE ════════
  {
    id: 'corporate-slate',
    name: 'Corporate',
    industry: 'Corporate',
    industryGroup: 'corporate',
    description: 'Refined slate and white for corporate professionals',
    font: 'Inter',
    headingFont: 'Inter',
    background: '#F8FAFC',
    surface: '#FFFFFF',
    primary: '#1E293B',
    secondary: '#0F172A',
    accent: '#3B82F6',
    text: '#0F172A',
    muted: '#64748B',
    border: '#E2E8F0',
    buttonStyle: 'filled',
    cardStyle: 'bordered',
    borderRadius: '8px',
    headerStyle: 'left',
    avatarShape: 'rounded',
    animation: 'none',
    enabledComponents: ['phone', 'email', 'linkedin', 'website', 'location', 'services', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: true,
    isPublished: true,
    isRecommended: true,
    tags: ['corporate', 'slate', 'professional', 'business', 'clean'],
  },
  {
    id: 'consultant',
    name: 'Consultant',
    industry: 'Consultant',
    industryGroup: 'corporate',
    description: 'Professional and trustworthy for consultants',
    font: 'Inter',
    headingFont: 'Raleway',
    background: '#FAFAF9',
    surface: '#FFFFFF',
    primary: '#1C4532',
    secondary: '#14532D',
    accent: '#6EE7B7',
    text: '#111827',
    muted: '#6B7280',
    border: '#E5E7EB',
    buttonStyle: 'outlined',
    cardStyle: 'flat',
    borderRadius: '8px',
    headerStyle: 'left',
    avatarShape: 'rounded',
    animation: 'subtle',
    enabledComponents: ['phone', 'email', 'linkedin', 'website', 'services', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: true,
    isPublished: true,
    isRecommended: false,
    tags: ['consultant', 'green', 'professional', 'trust', 'business'],
  },

  // ════════ INFLUENCER / CONTENT ════════
  {
    id: 'influencer-vibrant',
    name: 'Influencer',
    industry: 'Influencer',
    industryGroup: 'creative',
    description: 'Vibrant gradient card for social media influencers',
    font: 'Poppins',
    headingFont: 'Poppins',
    background: '#09090B',
    surface: '#18181B',
    primary: '#EC4899',
    secondary: '#DB2777',
    accent: '#A855F7',
    text: '#FAFAFA',
    muted: '#A1A1AA',
    border: '#27272A',
    buttonStyle: 'pill',
    cardStyle: 'glass',
    borderRadius: '24px',
    headerStyle: 'hero',
    avatarShape: 'circle',
    animation: 'smooth',
    enabledComponents: ['instagram', 'tiktok', 'youtube', 'twitter', 'facebook', 'whatsapp', 'email', 'website'],
    allowColorCustomization: true,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: true,
    tags: ['influencer', 'pink', 'social', 'content', 'vibrant', 'dark'],
  },

  // ════════ TRAVEL ════════
  {
    id: 'travel-agency',
    name: 'Travel Agency',
    industry: 'Travel Agency',
    industryGroup: 'travel',
    description: 'Vibrant sky and sand for travel professionals',
    font: 'Nunito',
    headingFont: 'Raleway',
    background: '#F0F9FF',
    surface: '#FFFFFF',
    primary: '#0369A1',
    secondary: '#0284C7',
    accent: '#BAE6FD',
    text: '#0C4A6E',
    muted: '#64748B',
    border: '#BAE6FD',
    buttonStyle: 'pill',
    cardStyle: 'soft',
    borderRadius: '20px',
    headerStyle: 'hero',
    avatarShape: 'circle',
    animation: 'smooth',
    enabledComponents: ['phone', 'whatsapp', 'email', 'website', 'instagram', 'location', 'services', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: true,
    tags: ['travel', 'sky-blue', 'tourism', 'adventure', 'friendly'],
  },

  // ════════ AUTOMOTIVE ════════
  {
    id: 'car-rental',
    name: 'Car Rental',
    industry: 'Car Rental',
    industryGroup: 'auto',
    description: 'Sleek dark automotive design',
    font: 'Inter',
    headingFont: 'Oswald',
    background: '#111111',
    surface: '#1A1A1A',
    primary: '#FAFAFA',
    secondary: '#E5E5E5',
    accent: '#EAB308',
    text: '#F9FAFB',
    muted: '#6B7280',
    border: '#2A2A2A',
    buttonStyle: 'filled',
    cardStyle: 'flat',
    borderRadius: '6px',
    headerStyle: 'cover',
    avatarShape: 'rounded',
    animation: 'subtle',
    enabledComponents: ['phone', 'whatsapp', 'location', 'services', 'priceList', 'googlemap', 'contact'],
    allowColorCustomization: true,
    allowFontCustomization: false,
    isPublished: true,
    isRecommended: false,
    tags: ['automotive', 'dark', 'yellow', 'car', 'rental', 'sleek'],
  },
];

// ─── HELPER FUNCTIONS ────────────────────────────────────────

export function getTemplateById(id: string): IndustryTemplate | undefined {
  return INDUSTRY_TEMPLATES.find(t => t.id === id);
}

export function getTemplatesByIndustry(industry: string): IndustryTemplate[] {
  return INDUSTRY_TEMPLATES.filter(t =>
    t.industry.toLowerCase().includes(industry.toLowerCase()) ||
    t.industryGroup.toLowerCase().includes(industry.toLowerCase())
  );
}

export function getRecommendedTemplates(industryGroup?: string): IndustryTemplate[] {
  return INDUSTRY_TEMPLATES.filter(t =>
    t.isPublished && (industryGroup ? t.industryGroup === industryGroup : t.isRecommended)
  );
}

export function templateToCssVars(tpl: IndustryTemplate): Record<string, string> {
  return {
    '--theme-background': tpl.background,
    '--theme-surface':    tpl.surface,
    '--theme-primary':    tpl.primary,
    '--theme-secondary':  tpl.secondary,
    '--theme-accent':     tpl.accent,
    '--theme-text':       tpl.text,
    '--theme-muted':      tpl.muted,
    '--theme-border':     tpl.border,
    '--theme-radius':     tpl.borderRadius,
    '--theme-font':       tpl.font,
    '--theme-heading-font': tpl.headingFont,
  };
}
