import { TemplateConfiguration } from './templateTypes';

export const templatesList: TemplateConfiguration[] = [
  {
    id: 'modern',
    name: 'Modern Clean',
    description: 'A vibrant modern look with rounded capsules and bright high-contrast blue actions.',
    primaryColor: '#2563EB',
    secondaryColor: '#3B82F6',
    backgroundColor: '#F8FAFC',
    textColor: '#0F172A',
    cardBgColor: '#FFFFFF',
    cardBorderColor: '#E2E8F0',
    borderRadius: '24px',
    fontFamily: 'Inter',
    buttonStyle: 'SOLID',
    spacing: 'NORMAL',
    headerStyle: 'CENTER',
    backgroundStyle: 'SOLID',
  },
  {
    id: 'minimal',
    name: 'Minimalist Monocle',
    description: 'Clean monochrome aesthetic with microborders and high-density typography.',
    primaryColor: '#000000',
    secondaryColor: '#1E293B',
    backgroundColor: '#FFFFFF',
    textColor: '#000000',
    cardBgColor: '#FFFFFF',
    cardBorderColor: '#F1F5F9',
    borderRadius: '8px',
    fontFamily: 'Inter',
    buttonStyle: 'OUTLINE',
    spacing: 'TIGHT',
    headerStyle: 'LEFT',
    backgroundStyle: 'SOLID',
  },
  {
    id: 'executive',
    name: 'Executive Slate',
    description: 'Professional navy tones with sharp angles for a polished premium presentation.',
    primaryColor: '#0F172A',
    secondaryColor: '#475569',
    backgroundColor: '#F1F5F9',
    textColor: '#0F172A',
    cardBgColor: '#FFFFFF',
    cardBorderColor: '#CBD5E1',
    borderRadius: '0px',
    fontFamily: 'Outfit',
    buttonStyle: 'SHADOW',
    spacing: 'NORMAL',
    headerStyle: 'CENTER',
    backgroundStyle: 'SOLID',
  },
  {
    id: 'elegant',
    name: 'Gold & Ivory',
    description: 'Warm champagne hues and refined serifs for a luxury executive presentation.',
    primaryColor: '#D97706',
    secondaryColor: '#F59E0B',
    backgroundColor: '#FCFBF7',
    textColor: '#1E1B4B',
    cardBgColor: '#FFFFFF',
    cardBorderColor: '#FEF3C7',
    borderRadius: '32px',
    fontFamily: 'Outfit',
    buttonStyle: 'SOLID',
    spacing: 'LOOSE',
    headerStyle: 'CENTER',
    backgroundStyle: 'SOLID',
  },
  {
    id: 'corporate',
    name: 'Corporate Shield',
    description: 'Standard secure grid system designed for corporate business cards.',
    primaryColor: '#1E3A8A',
    secondaryColor: '#3B82F6',
    backgroundColor: '#F8FAFC',
    textColor: '#1F2937',
    cardBgColor: '#FFFFFF',
    cardBorderColor: '#E5E7EB',
    borderRadius: '12px',
    fontFamily: 'Inter',
    buttonStyle: 'SOLID',
    spacing: 'NORMAL',
    headerStyle: 'LEFT',
    backgroundStyle: 'SOLID',
  },
  {
    id: 'creative',
    name: 'Creative Pop',
    description: 'Playful neon highlights and thick border-offsets for developers and artists.',
    primaryColor: '#D946EF',
    secondaryColor: '#EC4899',
    backgroundColor: '#FAFAF9',
    textColor: '#1C1917',
    cardBgColor: '#FFFFFF',
    cardBorderColor: '#F3F4F6',
    borderRadius: '24px',
    fontFamily: 'Outfit',
    buttonStyle: 'SHADOW',
    spacing: 'LOOSE',
    headerStyle: 'CENTER',
    backgroundStyle: 'SOLID',
  },
  {
    id: 'dark',
    name: 'Midnight Dark',
    description: 'Deep obsidian backdrop with emerald actions to minimize screen fatigue.',
    primaryColor: '#10B981',
    secondaryColor: '#059669',
    backgroundColor: '#0F172A',
    textColor: '#F8FAFC',
    cardBgColor: '#1E293B',
    cardBorderColor: '#334155',
    borderRadius: '16px',
    fontFamily: 'Inter',
    buttonStyle: 'SOLID',
    spacing: 'NORMAL',
    headerStyle: 'CENTER',
    backgroundStyle: 'SOLID',
  },
  {
    id: 'glass',
    name: 'Frosted Glass',
    description: 'Sleek frosted card layout layered over warm abstract vector backdrops.',
    primaryColor: '#6366F1',
    secondaryColor: '#818CF8',
    backgroundColor: '#EEF2FF',
    textColor: '#1E1B4B',
    cardBgColor: 'rgba(255, 255, 255, 0.4)',
    cardBorderColor: 'rgba(255, 255, 255, 0.6)',
    borderRadius: '28px',
    fontFamily: 'Outfit',
    buttonStyle: 'GLASS',
    spacing: 'NORMAL',
    headerStyle: 'GLASS_BANNER',
    backgroundStyle: 'MESH',
  },
  {
    id: 'gradient',
    name: 'Auro Gradient',
    description: 'Vibrant sunset gradients for a dynamic digital handshake.',
    primaryColor: '#F59E0B',
    secondaryColor: '#EF4444',
    backgroundColor: '#FFFBEB',
    textColor: '#451A03',
    cardBgColor: '#FFFFFF',
    cardBorderColor: '#FDE68A',
    borderRadius: '20px',
    fontFamily: 'Outfit',
    buttonStyle: 'SOLID',
    spacing: 'NORMAL',
    headerStyle: 'CENTER',
    backgroundStyle: 'GRADIENT',
  },
  {
    id: 'professional',
    name: 'Professional Teal',
    description: 'Restful teal colors and clean card dividers for healthcare and realtors.',
    primaryColor: '#0D9488',
    secondaryColor: '#14B8A6',
    backgroundColor: '#F0FDFA',
    textColor: '#115E59',
    cardBgColor: '#FFFFFF',
    cardBorderColor: '#CCFBF1',
    borderRadius: '16px',
    fontFamily: 'Inter',
    buttonStyle: 'SOLID',
    spacing: 'NORMAL',
    headerStyle: 'LEFT',
    backgroundStyle: 'SOLID',
  }
];

export function getTemplateById(id: string): TemplateConfiguration {
  return templatesList.find(t => t.id === id) || templatesList[0];
}
